--- 
title: "Documentation CarexNardus2021"
author: "Raphael S. von Büren"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Documentation of CarexNardus2021 study of Raphael S. von Büren and Erika Hiltbrunner, Department of Environmental Sciences, University of Basel."
---

```{r setup-index, include = FALSE, message = FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

# Libraries
library(tidyverse)

# Read documentation data (alle hier hinmachen aber mit # wenn ich sie nicht auf Homepage will)
raw_pos_char      <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_pos_characteristics.csv", col_names = T)
R_pos_temp        <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_R_pos_temperature.csv", col_names = T)
raw_moist         <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_moistmeasure_moisture.csv", col_names = T)
raw_pos_snow      <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_pos_snow.csv", col_names = T)
raw_pos_veg       <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_pos_vegetation.csv", col_names = T)
R_species_info    <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_R_species_information.csv", col_names = T)
raw_vig           <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_vigmeasure_vigour.csv", col_names = T)
raw_frost         <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_frostmeasure_freezingresistance.csv", col_names = T)
raw_soil          <- readr::read_csv(file = "docs/GitHub-documentation_files/doc_raw_pos_soil.csv", col_names = T)
```


# Prerequisites {}

This is a documentation book, providing details on **data structure** and **analyses** of the project "Contrasting range limits of the most abundant, alpine tussock graminoids _Carex curvula_ and _Nardus stricta_".

The **bookdown** package, used to create this book, can be installed from CRAN or Github:

```{r eval = FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

**The documentation was build with the following R version:**
```{r echo = FALSE, }
writeLines(R.version$version.string)
```